### ISSUE TITLE
Bercon maps crashes 3dsMax 2020

### ISSUE THREAD

**Issue by feimeng2017** [Bercon/BerconMaps#28] opened 2019-07-01 02:21 UTC

**Comment by Bercon** [comment] 2019-07-01 15:42
Is this duplicate of #12? Could you please confirm it's fixed in the latest version that was merged today?

**Comment by feimeng2017** [comment] 2019-07-05 14:10
下了最新版
max2020 完美
谢谢

**Comment by feimeng2017** [comment] 2019-07-05 14:11
Down to the latest edition

Max 2020 Perfect

Thank you

**Closed as completed** 2021-03-25 11:32 UTC
