### ISSUE TITLE
Bercon maps crashes 3dsMax 2018 on file save.

### ISSUE THREAD

**Issue by MadMikeDIG** [Bercon/BerconMaps#12] opened 2018-02-07 14:22 UTC
Bercon maps(except bercon tile) crashes 3dsMax 2018.4 on file save when it's applied to a material or light in the scene.

**Comment by feathered-arch** [comment] 2018-03-06 00:18
This happens for me on Update 2, unfortunately.

**Comment by feathered-arch** [comment] 2018-03-06 20:11
After further investigation I have discovered something very odd that I would like you to try to reproduce. 

If the material is first created in the SLATE editor, there is no crash. 

If the material is first created in the Compact material editor, however, the file will crash upon save. 

I'm afraid I don't know enough about Max's SDK or internals to understand why this may be.

**Comment by MadMikeDIG** [comment] 2018-03-06 20:14
I only ever work in Slate. I forgot compact was still a thing.

**Comment by kentebird** [comment] 2018-03-14 22:47
Please see [output from VS debugger](https://raw.githubusercontent.com/kentebird/BerconMaps/master/crashPoint.JPG)
and [VS debugger disassembly](https://raw.githubusercontent.com/kentebird/BerconMaps/master/crashPoint%20disassembler.JPG)

I do not have the QT framework PDB files, but I strongly suspect this is some sort of QT bug.

MAX2018 is able to reopen the saved file, and can then resave the file without any problems. But the minute you add any new Bercon maps it will crash again at save. 

I have also noticed that Bercon Tile does not seem to have this problem! (Although I can see no obvious reason for why...)

**Comment by kentebird** [comment] 2019-05-06 19:10
Continuing on this thread, I can confirm the crash happens because of the custom curve control.

Bercon Tile does not make use of this control and is therefore unaffected.

Eliminating curvectrl from the project will result in the problem being "fixed". I'm not really sure what the point of this control is, but I can see backward compatibility issues in scenes being present if it is eliminated.

**Comment by kentebird** [comment] 2019-05-12 21:28
Fixed. See https://github.com/kentebird/BerconMaps/tree/master/src/DLL for recompiled binaries for 2019-2020.

**Comment by Bercon** [comment] 2019-07-01 15:41
Could someone confirm that the merged pull request fixes the issue?

**Comment by kentebird** [comment] 2019-07-01 16:16
Yes, it does.

-James
347.866.5522 (vm/sms)

**Closed as completed** 2021-03-25 11:33 UTC
